version: '3.8'

services:

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/coworking
      DATABASE_USER: postgres
      DATABASE_PASSWORD: root
    ports:
      - "8080:8080"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: coworking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  liquibase:
    build:
      context: .
      dockerfile: Dockerfile.liquibase
    depends_on:
      - db
    environment:
      LIQUIBASE_URL: jdbc:postgresql://db:5432/coworking
      LIQUIBASE_USERNAME: postgres
      LIQUIBASE_PASSWORD: root
      LIQUIBASE_CHANGELOG_FILE: /liquibase/db/changelog/changelog.xml
    entrypoint: ["liquibase", "update"]

volumes:
  db_data:
