version: '3.8'

services:

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/coworking
      DATABASE_USER: postgres
      DATABASE_PASSWORD: root

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: coworking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
